### ISSUE TITLE
欧拉积分

### ISSUE THREAD

**Issue by Jimsysu** [zju3dv/PVIO#4]
PreIntegrator::increment 中预积分计算，这里使用欧拉法，dt是不是少乘了0.5 ?  
delta.q = (delta.q * expmap(w * dt)).normalized();

**Comment by wangq0688** [comment]
@Jimsysu  没有少乘啊

**Comment by Jimsysu** [comment]
> @Jimsysu 没有少乘啊

是没少乘，但是不明白那个四元数扰动更新的 1/2 去哪里了？

**Comment by wangq0688** [comment]
@Jimsysu  你说的是四元数的导数 ，  这是矩阵的导数

另外，你知道程序中位姿优化和平面处理的入口在哪吗？

**Comment by wangq0688** [comment]
@Jimsysu 关于旋转的更新方程，在秦永元《惯性导航》第一版P238 P292，有比较详细介绍。
expmap(w * dt) 我是通过微分方程理解的

**Comment by ybbbbt** [comment]
Hi @Jimsysu, 
expmap用的是Rodrigues，不是四元数更新。
您可以参考一下 https://en.wikipedia.org/wiki/Axis%E2%80%93angle_representation 或者https://fzheng.me/2018/05/22/quaternion-matrix-so3-jacobians/
