### ISSUE TITLE
代码入口

### ISSUE THREAD

**Issue by wangq0688** [zju3dv/PVIO#5]
大佬，能否告知位姿优化和平面检测的入口在哪，我这只菜鸡实在是没找到。。。。。。。

**Comment by ybbbbt** [comment]
Hi  @wangq0688,

VIP-PnP优化入口：
https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/core/sliding_window_tracker.cpp#L79
SlidingWindow优化入口：
https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/core/sliding_window_tracker.cpp#L113
唤起`PlaneExtractor`的平面提取：
https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/core/sliding_window_tracker.cpp#L136
