### ISSUE TITLE
some confusion about the ray direction?

### ISSUE THREAD

**Issue by cai199626** [zju3dv/PVIO#6]
thanks for your awesome work!
but i have some confusion about the code.

In the plane_extractor.cpp
```
void PlaneExtractor::extend_planes_and_cast_plane_points(double extend_rpe_ratio) {
    std::unique_lock planes_lock(planes_mutex);
    std::vector<Plane *> candidate_planes;
    std::vector<vector<3>> candidate_plane_points;
    for (size_t i = 0; i < map->track_num(); ++i) {
        Track *track = map->get_track(i);
        if (!track->flag(TrackFlag::TF_VALID)) continue; // it seems better to skip these invalid tracks
        vector<3> point = track->get_landmark_point();
        const auto &[frame_ref, keypoint_index_ref] = track->first_keypoint();
        const auto camera_ref_pose = frame_ref->get_pose(frame_ref->camera);
        double rpe_before_project = compute_reprojection_error(map, track, point);
        vector<3> direction = camera_ref_pose.q * frame_ref->get_keypoint(keypoint_index_ref).homogeneous();  // may be wrong?
```

the direction compute by R * [u,v,1], but it should be R*K^ * [u,v,1]?
K^ is the inverse of the intrinsic?

**Comment by elegracer** [comment]
Hi, the result of `Frame::get_keypoint(...)` is an `Eigen::Vector2d` variable which lies in the camera's normalized plane (z = 1).

https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/map/frame.h#L62-L64

This step is done during keypoint detection,

https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/map/frame.cpp#L72-L87

using `remove_k` to apply the **K^{-1}** left multiplication you mentioned above.

https://github.com/zju3dv/PVIO/blob/a6acc8a2d26d2c8eca5e16d2e66e450a72b2dd49/pvio/src/pvio/geometry/stereo.h#L29-L31

So, to wrap up, `frame_ref->get_keypoint(keypoint_index_ref).homogeneous()` is of type `Eigen::Vector3d`, meaning the 3d coordinate of this keypoint in the corresponding camera's normalized plane, which does not need another **K^{-1}** left multiplication.
